3/PSI/PSI3/kahootclone/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('models/', include('models.urls'), name="models"),
    path('', RedirectView.as_view(url='models/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('services/', include('services.urls'), name='services')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

3/PSI/PSI3/models/urls.py
from django.urls import path
from django.conf.urls import url
from models import views as core_views
from . import views

urlpatterns = [
    path('', views.index, name='home_unsigned'),
    url(r'^signup/$', core_views.signup, name='signup')
]

3/PSI/PSI3/models/admin.py
from django.contrib import admin
from .models import Questionnaire, Question, Answer, Game, Participant, Guess, User


# Register your models here.
admin.site.register(Questionnaire)
admin.site.register(Question)
admin.site.register(Answer)
admin.site.register(Game)
admin.site.register(Participant)
admin.site.register(Guess)
admin.site.register(User)

3/PSI/PSI3/models/apps.py
from django.apps import AppConfig


class ModelsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'models'

3/PSI/PSI3/models/constants.py
WAITING = 1
QUESTION = 2
ANSWER = 3
LEADERBOARD = 4

3/PSI/PSI3/models/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields

3/PSI/PSI3/models/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
import random
import uuid
WAITING = 1
QUESTION = 2
ANSWER = 3
LEADERBOARD = 4


# TODO You need to create your oen class inherity from UserCreationForm
# and we must redefine the meta.

class User(AbstractUser):
    # Tambien authenticate?
    pass


class Questionnaire(models.Model):

    title = models.CharField(max_length=100)
    created_at = models.DateTimeField('created at', auto_now_add=True)
    updated_at = models.DateTimeField('updated at', auto_now=True)
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('questionnaire-detail', args=[str(self.id)])

    def __str__(self):
        return self.title


class Question(models.Model):

    # question_id = models.UUIDField(primary_key=True, default=uuid.uuid4,
    #                                help_text="Unique id for question")
    question = models.TextField(max_length=500, help_text="Write the question")
    questionnaire = models.ForeignKey('Questionnaire',
                                      on_delete=models.CASCADE,
                                      )
    created_at = models.DateTimeField('created at', auto_now_add=True)
    updated_at = models.DateTimeField('updated at', auto_now=True)
    answerTime = models.PositiveIntegerField(
        'answer time',
        null=True,
        blank=True
    )
    noAnswer = models.PositiveIntegerField(
        'number answer',
        primary_key=False,
        validators=[MaxValueValidator(4), MinValueValidator(0)],
        default=0
    )

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('question-detail', args=[str(self.id)])

    def __str__(self):
        return self.question


class Answer(models.Model):
    # answer_id = models.UUIDField(primary_key=True, default=uuid.uuid4,
    #                              help_text="Unique id for answer")
    answer = models.TextField(max_length=500, help_text="Write the answer")
    question = models.ForeignKey('Question', on_delete=models.CASCADE,
                                 )
    correct = models.BooleanField('correct')

    def save(self, *args, **kwargs):

        if self.pk is None:
            self.question.noAnswer += 1

        elif self.correct and not Answer.objects.filter(
            question=self.question, correct=True
                ).exclude(pk=self.pk).exists():
            self.question.noAnswer = 4 - Answer.objects.filter(
                question=self.question).exclude(pk=self.pk).count()

        self.question.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        question = self.question
        super().delete(*args, **kwargs)

        question.noAnswer = Answer.objects.filter(question=question).count()
        question.save()

    def __str__(self):
        return self.answer


class Game(models.Model):

    # game_id = models.UUIDField(primary_key=True, default=uuid.uuid4,
    #                            help_text="Unique id for game")
    questionnaire = models.ForeignKey('Questionnaire',
                                      on_delete=models.CASCADE,
                                      )
    created_at = models.DateTimeField('created at', auto_now_add=True)

    class GameState(models.IntegerChoices):
        WAITING = WAITING
        QUESTION = QUESTION
        ANSWER = ANSWER
        LEADERBOARD = LEADERBOARD
    state = models.IntegerField(choices=GameState.choices)

    """
    The attribute game.publicId is a unique integer number
    (as the primary key) in the [1 - 10] range
    """

    num = random.randint(1, 1000000)
    publicId = models.IntegerField(
        default=num,
        help_text="Unique public id for game"
    )

    countdownTime = models.PositiveIntegerField('countdown time',
                                                )
    questionNo = models.IntegerField("Question number", default=1)

    def __str__(self):
        return str(self.publicId)


class Participant(models.Model):

    participant_id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                                      help_text="Unique id for participant")
    game = models.ForeignKey('Game', on_delete=models.CASCADE)
    alias = models.CharField(max_length=100)
    points = models.PositiveBigIntegerField('Points')
    uuidP = models.UUIDField(primary_key=False, default=uuid.uuid4,
                             help_text="Unique public id for participant")

    def __str__(self):
        return self.alias


class Guess(models.Model):

    guess_id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                                help_text="Unique id for guess")

    # Repasar el on_delete
    participant = models.ForeignKey('Participant', on_delete=models.CASCADE)

    game = models.ForeignKey('Game', on_delete=models.CASCADE)

    question = models.ForeignKey('Question', on_delete=models.CASCADE)

    answer = models.ForeignKey('Answer', on_delete=models.CASCADE)

    def __str__(self):
        return '{0}: {1}'.format(self.participant, self.answer)

3/PSI/PSI3/models/tests.py
from django.test import TestCase

# Create your tests here.

3/PSI/PSI3/models/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
# Create your views here.


def index(request):

    return render(request, 'home_unsigned.html')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home_signed')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

3/PSI/PSI3/services/models.py
# Create your models here.

3/PSI/PSI3/models/templates/models/answer_remove.html
{% extends "base.html" %}

{% block content %}

<h2>Remove answer</h2>

<p>Are you sure you want to remove the answer: {{ answer }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes" />
</form>

{% endblock %}

3/PSI/PSI3/models/templates/models/game_countdown_answer.html
{% extends "base.html" %}

{% block content %}

<h2>Correct Answer:</h2>
{% for answer in answers %}
    {% if answer.correct %}
        {{ answer.answer }}
    {% endif %}
{% endfor %}

<h2>Participant's Score</h2>
{% for participant in participants %}
    {{participant.alias}} ({{participant.points}})
{% endfor %}
<button onclick="window.location.href='{% url 'game-countdown-leaderboard' game.id %}'">Leaderboard</button>
{% endblock %}

3/PSI/PSI3/models/templates/models/game_countdown_leaderboard.html
{% extends "base.html" %}

{% block content %}
<h2>Leaderboard</h2>

{% for participant in participants%}
<p>{{participant.alias}} {{participant.points}}</p>
{% endfor %}
<button onclick="window.location.href='{% url 'game-countdown-question' game.id %}'">Next question</button>

{% if game.questionNo < 2 %}
<button onclick="window.location.href='{% url 'home_signed' %}'">End of Kahoot</button>
{% endif %}

{% endblock %}

3/PSI/PSI3/models/templates/models/game_countdown_question.html
{% extends "base.html" %}

{% block content %}

<h2>Question:</h2> {{ question }}

<h2>Answers:</h2>

{% for answer in answers %}
    <td>
        <p>{{ answer.answer }}</p>
    </td>
{% endfor %}

<button onclick="window.location.href='{% url 'game-countdown-answer' game.id %}'">Show Answer</button>
{% endblock %}

3/PSI/PSI3/models/templates/models/game_countdown_waiting.html
{% extends "base.html" %}

{% block content %}
<h2>We will start in {{game.countdownTime}} seconds</h2>
<button onclick="window.location.href='{% url 'game-countdown-question' game.id %}'">Next question</button>
{% endblock %}

3/PSI/PSI3/models/templates/models/game_detail.html
{% extends "base.html" %}

{% block content %}
{% load static %}

PIN code: {{ game.publicId }}

<button onclick="window.location.href='{% url 'game-countdown-waiting' game.id %}'">Get started</button>
{% include "models/game_update_participants.html" %}

{% endblock %}

3/PSI/PSI3/models/templates/models/game_form.html
{% extends "base.html" %}

{% block content %}

<h2>NEW GAME</h2>

<form action="" method="post"> 
    {% csrf_token %}
    Countdown time: <input type="number" name="countdownTime">
    {% if questionnaire %}
        <a href="{% url 'questionnaire-detail' questionnaire.id %}">Cancel</a>
    {% else %}
        <a href="{% url 'questionnaire-list'  %}">Cancel</a>
    {% endif %}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

3/PSI/PSI3/models/templates/models/game_update_participants.html
{% block content %}
<h3>List of participants</h3>
<u1 id="participants">
    
</u1>


<script>
    function updateParticipants() {
        fetch("{% url 'game-update-participant' game.publicId %}", {
            headers: {
                "Accept": "application/json"
            }
        }).then(response => {
            console.log("Response de update", response);
            if (!response.ok) {
                throw new Error("Network response was not ok");
            }
            return response.json();
        })
        .then(data => {
            // update the HTML with the new data
            var participantsDiv = document.getElementById("participants");
            //participantsDiv.innerHTML = data;
            participantsDiv.innerHTML = ''; // clear the previous content
            data.forEach(function(participant) {
                var li = document.createElement("li");
                li.innerText = participant.alias;
                participantsDiv.appendChild(li);
            });
        })
        .catch(error => {
            console.error("Error fetching data:", error);
        });
    }
</script>
<script>
    setInterval(updateParticipants, 2000); // call updateParticipants() every 2 seconds
</script>

{% endblock %}

3/PSI/PSI3/models/templates/models/question_form.html
{% extends "base.html" %}

{% block content %}

<h2>Create or Update Question</h2>

<form action="" method="post"> 
    {% csrf_token %}
    Question: <input type="text" name="question">
    Answer time: <input type="number" name="answerTime">
    {% if questionnaire %}
        <a href="{% url 'questionnaire-detail' questionnaire.id %}">Cancel</a>
    {% else %}
        <a href="{% url 'question-detail' question.id %}">Cancel</a>
    {% endif %}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

3/PSI/PSI3/models/templates/models/question_remove.html
{% extends "base.html" %}

{% block content %}

<h2>Remove question</h2>

<p>Are you sure you want to remove the question: {{ question }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes" />
</form>

{% endblock %}

3/PSI/PSI3/models/templates/models/questionnaire_confirm_remove.html
{% extends "base.html" %}

{% block content %}

<h2>Delete Questionnaire</h2>

<p>Are you sure you want to delete the questionnaire: {{ questionnaire }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

3/PSI/PSI3/models/templates/models/questionnaire_detail.html
{% extends "base.html" %}

{% block content %}
  <h2>Questionnaire Detail</h2>
  <h3>{{ questionnaire.title }}</h3>
  <button onclick="window.location.href='{% url 'questionnaire-update' questionnaire.pk %}'">Edit title</button>
  <button onclick="window.location.href='{% url 'game-create' questionnaire.pk %}'">Play Game</button>
  <div>
    {% if questionnaire.question_set.all %}
      <table>
        <tr>
          <th>Question</th>
          <th>No answers</th>
        </tr>
        {% for question in questionnaire.question_set.all %}
        <tr>
          <td>
            <a href="{{ question.get_absolute_url}}">{{ question.question }}</a>
          </td>
          <td>
            <p>{{ question.noAnswer }}</p>
          </td>
          <td>
            <button onclick="window.location.href='{% url 'question-remove' question.pk %}'">Remove</button>
          </td>
        </tr>
        {% endfor %}
      </table>
        
    {% else %}
        <p>There are no questions in the Questionnaire.</p>
    {% endif %}
    <div>
      <button onclick="window.location.href='{% url 'question-create' questionnaire.pk %}'">Add New Question</button>
      <button onclick="window.location.href='{% url 'questionnaire-list' %}'">Back to questionnaire list</button>
    </div>
  </div>

{% endblock %}

3/PSI/PSI3/models/templates/models/questionnaire_form.html
{% extends "base.html" %}

{% block content %}

<h2>Create or Update Questionnaire</h2>

<form action="" method="post"> 
    {% csrf_token %}
    Title: <input type="text" name="title">
    <a href="{% url 'home_signed' %}">Cancel</a>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

3/PSI/PSI3/models/templates/models/questionnaire_list.html
{% extends "base.html" %}
{% block content %}

  <h2>Questionnaire List</h2>
  {% if questionnaire_list %}
    {% for quest in questionnaire_list %}
      <p>
        <a href="{{quest.get_absolute_url }}">{{quest.title}}</a>
          <button onclick="window.location.href='{% url 'questionnaire-confirm-remove' quest.pk %}'">Delete</button>
        </p>
    {% endfor %}
  
  {% else %}
    <p>You still don't have any Questionnaires.</p>
  {% endif %}
  
{% endblock %}